"""Canonical error codes for tool failure normalization."""

# Generic
TOOL_UNSTRUCTURED_RESULT = "TOOL_UNSTRUCTURED_RESULT"

# File tools
FILE_PATH_NOT_FOUND = "FILE_PATH_NOT_FOUND"
FILE_FILE_NOT_FOUND = "FILE_FILE_NOT_FOUND"
FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS"
FILE_LIST_FAILED = "FILE_LIST_FAILED"
FILE_READ_FAILED = "FILE_READ_FAILED"
FILE_WRITE_FAILED = "FILE_WRITE_FAILED"
FILE_MAKE_DIR_FAILED = "FILE_MAKE_DIR_FAILED"
FILE_KNOWLEDGE_PATH_OUTSIDE_ROOT = "FILE_KNOWLEDGE_PATH_OUTSIDE_ROOT"

# Execution tools
EXEC_SCRIPT_NOT_FOUND = "EXEC_SCRIPT_NOT_FOUND"
EXEC_EXIT_NONZERO = "EXEC_EXIT_NONZERO"
EXEC_TIMEOUT = "EXEC_TIMEOUT"
EXEC_RUNTIME_ERROR = "EXEC_RUNTIME_ERROR"
EXEC_PACKAGE_INSTALL_FAILED = "EXEC_PACKAGE_INSTALL_FAILED"

# Git tools
GIT_NOT_INSTALLED = "GIT_NOT_INSTALLED"
GIT_TIMEOUT = "GIT_TIMEOUT"
GIT_COMMAND_FAILED = "GIT_COMMAND_FAILED"
GIT_RUNTIME_ERROR = "GIT_RUNTIME_ERROR"

# Info tools
INFO_TOKEN_USAGE_UNAVAILABLE = "INFO_TOKEN_USAGE_UNAVAILABLE"
INFO_TIME_FORMAT_ERROR = "INFO_TIME_FORMAT_ERROR"
INFO_MATH_UNSOLVABLE = "INFO_MATH_UNSOLVABLE"

# RAG tools
RAG_NO_RESULTS = "RAG_NO_RESULTS"
RAG_SEARCH_FAILED = "RAG_SEARCH_FAILED"
RAG_REFRESH_FAILED = "RAG_REFRESH_FAILED"

# Vision tools
VISION_MODEL_UNAVAILABLE = "VISION_MODEL_UNAVAILABLE"
VISION_ANALYSIS_FAILED = "VISION_ANALYSIS_FAILED"
